### Get all users
GET http://localhost:4000/api/v1/course/django
Accept: application/json

###

### Get a single user
GET http://localhost:4000/api/v1/api-me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzQ1NDc5NDE2LCJleHAiOjE3NDU5MTE0MTZ9.hIen-c9wba8s-Qk6Yi1SyR0cvC3bRamEXRqX2M76jwY

### Get a single user
GET http://localhost:4000/api/v1/api-quizzes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzQ1NDc5NDE2LCJleHAiOjE3NDU5MTE0MTZ9.hIen-c9wba8s-Qk6Yi1SyR0cvC3bRamEXRqX2M76jwY

### Get a single user
GET http://localhost:4000/api/v1/quiz-results
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzQ1NDc5NDE2LCJleHAiOjE3NDU5MTE0MTZ9.hIen-c9wba8s-Qk6Yi1SyR0cvC3bRamEXRqX2M76jwY


###

### Create a new user
POST http://localhost:4000/api/v1/api-login
Content-Type: application/json

{
  "email": "jems@mailinator.com",
  "password": "12345678"
}

### Create a new user
POST http://localhost:4000/api/v1/api-password/update
Content-Type: application/json

{
  "newPassword": "123456",
  "confirmPassword": "123456",
  "confirmPassword": "12345678"
}

### Create a new user
POST http://localhost:4000/api/v1/reset-password
Content-Type: application/json

{
  "email": "jems@mailinator.com",
  "newPassword": "123456",
  "code":"6B2B79"
}

### Create a quiz
POST https://quiz-sw6o.onrender.com/api/v1/quiz-submit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTc0NTU4NDc3OSwiZXhwIjoxNzQ2MDE2Nzc5fQ.rSt7oH4mLS_Z3utYyaNlLI3SxqfToML7QE7sR8SPKZo


{
  "attempted": "2",
  "correct": "2",
  "quiz_id": "4",
  "quiz_title": "React Quiz",
  "total_questions": "2",
  "wrong": "0"
  
}

###

### Update a user
PUT http://localhost:4000/api/v1/api-password/reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzQ1NTA0MDQwLCJleHAiOjE3NDU5MzYwNDB9.zZdBXkjDF7u9R0SxcI0NUnJ0SMfnkuI7vpUdVFGUwiE
Content-Type: application/json

{
  "password": "123456",
  "confirmPassword": "123456"
}

###

### Delete a user
DELETE https://jsonplaceholder.typicode.com/users/1
